server:
  port: 8080
spring:
  application:
    name: simple-tools
  profiles:
    active: dev

---

spring:
  config:
    activate:
      on-profile: dev


---
##To set the Environment variables: --spring.profiles.active=sit

spring:
  config:
    activate:
      on-profile: sit

  mongo:
    connection: mongodb://localhost:27017/test?retryWrites=false
    database: test