server:
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keys/simpledemo.p12
    key-store-password: simpledemo.sp
    key-alias: simpledemo
    enabled: true #Here to turn on/off https
  port: 18888
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: simple-tools
  profiles:
    active: dev
  config:
    import:
      - optional:c:/myconfigs/app.yml
---

spring:
  config:
    activate:
      on-profile: dev


##Below part moved to "c:/myconfigs/app.yml"
#---
##To set the Environment variables: --spring.profiles.active=sit
#spring:
#  config:
#    activate:
#      on-profile: sit
#
#  mongo:
#    connection: mongodb://localhost:27017/test?retryWrites=false
#    database: test